# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 06:39
from __future__ import unicode_literals

import common.utils
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='邮箱')),
                ('role', models.CharField(blank=True, choices=[('Admin', '系统管理员'), ('User', '普通用户'), ('linkman', '联系人')], default='User', max_length=30, verbose_name='网管系统角色')),
                ('avatar', models.ImageField(null=True, upload_to='avatar', verbose_name='头像')),
                ('wechat', models.CharField(blank=True, max_length=30, verbose_name='微信')),
                ('dingtalk', models.CharField(blank=True, max_length=30, verbose_name='钉钉')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='部门')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('is_first_login', models.BooleanField(default=False)),
                ('date_expired', models.DateTimeField(blank=True, default=common.utils.date_expired_default, null=True, verbose_name='过期时间')),
                ('created_by', models.CharField(default='', max_length=30, verbose_name='创建人')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, verbose_name='用户名')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(db_index=True, max_length=30, verbose_name='邮箱')),
                ('role', models.CharField(blank=True, choices=[('Admin', '系统管理员'), ('User', '普通用户'), ('linkman', '联系人')], default='User', max_length=30, verbose_name='网管系统角色')),
                ('avatar', models.TextField(max_length=100, null=True, verbose_name='头像')),
                ('wechat', models.CharField(blank=True, max_length=30, verbose_name='微信')),
                ('dingtalk', models.CharField(blank=True, max_length=30, verbose_name='钉钉')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='部门')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('date_expired', models.DateTimeField(blank=True, default=common.utils.date_expired_default, null=True, verbose_name='过期时间')),
                ('created_by', models.CharField(default='', max_length=30, verbose_name='创建人')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('is_discard', models.BooleanField(default=False, verbose_name='is discard')),
                ('discard_time', models.DateTimeField(blank=True, null=True, verbose_name='discard time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.UserGroup', verbose_name='用户组'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
