# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职位'),
        ),
    ]
