#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views.zabbix import *

urlpatterns = [
    url(r'^$', host_list, name='host_list'),
    url(r'^node_add/$', node_add, name='node_add'),
    url(r'^node_list/$', node_list, name='node_list'),
    url(r'^node_list_json/$', node_list_json, name='node_list_json'),
    url(r'^node_edit/$', node_edit, name='node_edit'),
    url(r'^node_del/$', node_del, name='node_del'),
    url(r'^host_list/$', host_list, name='host_list'),
    url(r'^sync_zabbix_all', sync_zabbix_all, name='sync_zabbix_all'),
    url(r'^host_list_json/$', host_list_json, name='host_list_json'),
    url(r'^host_sync_zabbix/$', host_sync_zabbix, name='host_sync_zabbix'),
    url(r'^host_add/$', host_add, name='host_add'),
    url(r'^host_edit/$', host_edit, name='host_edit'),
    url(r'^host_del/$', host_del, name='host_del'),
    url(r'^group_list/$', group_list, name='group_list'),
    url(r'^group_list_json/$', group_list_json, name='group_list_json'),
    url(r'^group_get_host/$', group_get_host, name='group_get_host'),
    url(r'^group_save/$', group_save, name='group_save'),
    url(r'^group_add/$', group_add, name='group_add'),
    url(r'^group_edit/$', group_edit, name='group_edit'),
    url(r'^group_del/$', group_del, name='group_del'),
    url(r'^template_list/$', template_list, name='template_list'),
    url(r'^template_list_json/$', template_list_json, name='template_list_json'),
    url(r'^template_sync_zabbix/$', template_sync_zabbix, name='template_sync_zabbix'),
    url(r'^template_get_host/$', template_get_host, name='template_get_host'),
    url(r'^template_add/$', template_add, name='template_add'),
    url(r'^template_del/$', template_del, name='template_del'),
    url(r'^item_list/$', item_list, name='item_list'),
    url(r'^item_list_json/$', item_list_json, name='item_list_json'),
    url(r'^item_sync_zabbix/$', item_sync_zabbix, name='item_sync_zabbix'),
    url(r'^item_get_key/$', item_get_key, name='item_get_key'),
    url(r'^item_get_key/$', item_get_key, name='item_get_key'),
    url(r'^item_add/$', item_add, name='item_add'),
    url(r'^item_edit/$', item_edit, name='item_edit'),
    url(r'^item_del/$', item_del, name='item_del'),
    url(r'^trigger_list/$', trigger_list, name='trigger_list'),
    url(r'^tri_add_item/$', tri_add_item, name='tri_add_item'),
    url(r'^trigger_list_json/$', trigger_list_json, name='trigger_list_json'),
    url(r'^trigger_sync_zabbix/$', trigger_sync_zabbix, name='trigger_sync_zabbix'),
    url(r'^trigger_add/$', trigger_add, name='trigger_add'),
    url(r'^trigger_edit/$', trigger_edit, name='trigger_edit'),
    url(r'^trigger_del/$', trigger_del, name='trigger_del'),
]