# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('login_type', models.CharField(choices=[('W', 'Web'), ('ST', 'SSH Terminal')], max_length=2, verbose_name='Login type')),
                ('login_ip', models.GenericIPAddressField(verbose_name='Login ip')),
                ('login_city', models.CharField(blank=True, max_length=254, null=True, verbose_name='Login city')),
                ('user_agent', models.CharField(blank=True, max_length=254, null=True, verbose_name='User agent')),
                ('date_login', models.DateTimeField(auto_now_add=True, verbose_name='Date login')),
            ],
            options={
                'db_table': 'login_log',
                'ordering': ['-date_login', 'username'],
            },
        ),
    ]
